### ISSUE TITLE
Station-board will hang after a while

### ISSUE THREAD

**Issue by sysfranz** [mscharl/MMM-oebb-station-board#3]
Hi Michael,
I'm using Version 0.0.0 (?) of station-board with this config:
```
   {
      module: 'MMM-oebb-station-board',
      position: "top_left",
      config: 
      {
         stationNumber:1231823,
         connectionTypes:
         {
            Regional: true,
         }
      }
   },
``` 
After apx. one hour the station-board stops loading and the following errors are logged:
```
0|mm       | (node:8924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 36)
0|mm       | TypeError: Cannot read property 'replace' of undefined
0|mm       |     at Request.request [as _callback] (/home/pi/MagicMirror/modules/MMM-oebb-station-board/node_modules/oebb-api/oebb.js:309:33)
0|mm       |     at self.callback (/home/pi/MagicMirror/modules/MMM-oebb-station-board/node_modules/request/request.js:185:22)
0|mm       |     at Request.emit (events.js:182:13)
0|mm       |     at Request.onRequestError (/home/pi/MagicMirror/modules/MMM-oebb-station-board/node_modules/request/request.js:881:8)
0|mm       |     at ClientRequest.emit (events.js:182:13)
0|mm       |     at Socket.socketErrorListener (_http_client.js:382:9)
0|mm       |     at Socket.emit (events.js:182:13)
0|mm       |     at emitErrorNT (internal/streams/destroy.js:82:8)
0|mm       |     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
0|mm       |     at process._tickCallback (internal/process/next_tick.js:63:19)
0|mm       | (node:8924) UnhandledPromiseRejectionWarning: Error: read ECONNRESET
0|mm       |     at TCP.onread (net.js:657:25)
0|mm       | (node:8924) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 37)
```
BR, Franz

**Comment by burnydoom** [comment]
I love this module. Great work.

I have a similar issue. The departure times will not update / reload after a while so it keeps stuck. I work around by refreshing the browser with a <meta entry>.

Is there an option planned to add a "updateInterval" setting (similar to as in the MMM-WienerLinien module)? Maybe this would be a fix?
